services:
  web_testdjango:
    container_name: testdjango_con
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - database

  database:
    container_name: postgres_testdjango
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      DATABASE_HOST: ${PG_HOST}
      POSTGRESS_USER: ${PG_USER}
      POSTGRESS_PASSWORD: ${PG_PASSWORD}
      POSTGRESS_DB: ${PG_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}