# Generated by Django 4.2.11 on 2024-05-15 16:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fullname', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('typedoc', models.CharField(choices=[('Nit', 'Nit'), ('CC', 'Cc')], max_length=4)),
                ('nroDoc', models.CharField(max_length=14)),
                ('gender', models.CharField(choices=[('Masculino', 'Male'), ('Femenino', 'Femi')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
    ]
